#!/bin/bash

scriptpath="$(readlink -f "$0")"
workdir="${scriptpath%/*}"
cd "${workdir}/../.."

. "ci/ci_scripts/common.sh"

if docker ps --format '{{.Names}}' | grep -q "^$name$"; then
    echo "Container is running. Stopping it..."
    docker stop $name
    docker rm $name
    docker run -d --restart always -e NEXTAUTH_SECRET="${NEXTAUTH_SECRET}" -e NEXT_PUBLIC_URL="${NEXT_PUBLIC_URL}" -e NEXT_PUBLIC_API_URL="${NEXT_PUBLIC_API_URL}" -e  NEXTAUTH_URL="${NEXTAUTH_URL}" -e NEXT_PUBLIC_RECAPTCHA_SITE_KEY="${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}" -e NEXT_PUBLIC_SEAMETRIX_KEY="${NEXT_PUBLIC_SEAMETRIX_KEY}" -e RECAPTCHA_SECRET_KEY="${RECAPTCHA_SECRET_KEY}" -e NEXT_PUBLIC_STRAPI_API_URL="${NEXT_PUBLIC_STRAPI_API_URL}" -e NEXT_PUBLIC_RT_URL="${NEXT_PUBLIC_RT_URL}" -e BACKEND_API_URL="${BACKEND_API_URL}" -e IDENTITY_API_URL="${IDENTITY_API_URL}" -e NEXT_PUBLIC_FILE_API_URL="${NEXT_PUBLIC_FILE_API_URL}" -e NEXT_PUBLIC_SEAMETRIX_API_URL="${NEXT_PUBLIC_SEAMETRIX_API_URL}" -e IDENTITY_API_CLIENT_ID="${IDENTITY_API_CLIENT_ID}" -e IDENTITY_API_CLIENT_SECRET="${IDENTITY_API_CLIENT_SECRET}" -e IDENTITY_API_GRANT_TYPE="${IDENTITY_API_GRANT_TYPE}" -e IDENTITY_TOKEN_GRANT_TYPE="${IDENTITY_TOKEN_GRANT_TYPE}" -e PREVIEW_SECRET="${PREVIEW_SECRET}" --name ${name} -p 3000:3000 "${name}:${version}"
fi

if docker ps -a --format '{{.Names}}' | grep -q "^$name$"; then
    echo "Container $name exists. Removing it..."
    docker rm $name
else
    echo "Container $name does not exist."
fi
docker run -d --restart always -e NEXTAUTH_SECRET="${NEXTAUTH_SECRET}" -e NEXT_PUBLIC_URL="${NEXT_PUBLIC_URL}" -e NEXT_PUBLIC_API_URL="${NEXT_PUBLIC_API_URL}" -e  NEXTAUTH_URL="${NEXTAUTH_URL}" -e NEXT_PUBLIC_RECAPTCHA_SITE_KEY="${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}" -e NEXT_PUBLIC_SEAMETRIX_KEY="${NEXT_PUBLIC_SEAMETRIX_KEY}" -e RECAPTCHA_SECRET_KEY="${RECAPTCHA_SECRET_KEY}" -e NEXT_PUBLIC_STRAPI_API_URL="${NEXT_PUBLIC_STRAPI_API_URL}" -e NEXT_PUBLIC_RT_URL="${NEXT_PUBLIC_RT_URL}" -e BACKEND_API_URL="${BACKEND_API_URL}" -e IDENTITY_API_URL="${IDENTITY_API_URL}" -e NEXT_PUBLIC_FILE_API_URL="${NEXT_PUBLIC_FILE_API_URL}" -e NEXT_PUBLIC_SEAMETRIX_API_URL="${NEXT_PUBLIC_SEAMETRIX_API_URL}" -e IDENTITY_API_CLIENT_ID="${IDENTITY_API_CLIENT_ID}" -e IDENTITY_API_CLIENT_SECRET="${IDENTITY_API_CLIENT_SECRET}" -e IDENTITY_API_GRANT_TYPE="${IDENTITY_API_GRANT_TYPE}" -e IDENTITY_TOKEN_GRANT_TYPE="${IDENTITY_TOKEN_GRANT_TYPE}" -e PREVIEW_SECRET="${PREVIEW_SECRET}" --name ${name} -p 3000:3000 "${name}:${version}"